FROM maven:3.6.0-jdk-11-slim AS build
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package

#FROM openjdk:latest
#COPY --from=MAVEN_TOOL_CHAIN target/MovieInfoService-0.0.1-SNAPSHOT.jar /app.jar
#CMD ["java", "-jar", "/app.jar"]
#EXPOSE 8081