#FROM maven:3.6.0-jdk-11-slim AS build
#COPY src /home/app/src
#COPY pom.xml /home/app
#RUN mvn -f /home/app/pom.xml clean package
FROM openjdk:11-jre-slim
WORKDIR /vivek
COPY . ./vivek
RUN cd /vivek/MovieInfoService/target
RUN pwd
RUN ls
EXPOSE 8081
ENTRYPOINT ["java","-jar","target/MovieInfoService-0.0.1-SNAPSHOT.jar"]