#FROM maven:3.6.0-jdk-11-slim AS build
#COPY src /home/app/src
#COPY pom.xml /home/app
#RUN mvn -f /home/app/pom.xml clean package

FROM openjdk:11-jre-slim
# RUN mkdir -p /vivek
# WORKDIR /vivek
COPY . /vivek
RUN pwd
RUN ls
# COPY /jenkins/workspace/maven_project/MovieInfoService/target/MovieInfoService-0.0.1-SNAPSHOT.jar demo.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","target/MovieInfoService-0.0.1-SNAPSHOT.jar"]