node {
    stage("clean workspace") {
        deleteDir()
    }
    stage("git checkout") {
        checkout scm
    }
    stage("mvn build") {
        echo "PATH = ${PATH}"
        dir("MovieInfoService") {
            sh "ls"
            sh "pwd"
            sh "mvn clean install -DskipTests"
        }
    }
    stage("docker build") {
        sh "sudo docker build -t movieinfo ."
        sh "sudo docker images"
        sh "sudo docker ps"
    }
    stage("docker run") {
        sh "sudo docker run -p 8081:8081 movieinfo ."
        sh "sudo docker images"
        sh "sudo docker ps"
    }
}