node {
    stage("clean workspace") {
        deleteDir()
    }
    stage("git checkout") {
        checkout scm
    }
    stage("mvn build") {
        echo "PATH = ${PATH}"
        dir("MovieInfoService") {
            sh "ls"
            sh "pwd"
            sh "mvn clean install -DskipTests"
        }
    }
}